[package]
name = "inkscape"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
derive_more = "0.99.17"
image = "0.24.3"
quick-xml = "0.25.0"
thiserror = "1.0.34"
